title: First Last / 中文
url: "https://gangliu-code.github.io"
baseurl: "/"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
# ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Templated adapted from Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://gangliu-code.github.io"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
